### ISSUE TITLE
Make renaming keys easier

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/mementifier#17]
Right now it is hard to use a different name in the memento of an object than the defined name of the property.  For instance, it is not easy to change `unreadMessages` to `unread` in the memento.  You can do this using mappers and deleting the old keys, but it would be nice for Mementifier to handle this.  I propose borrowing from SQL and using the `AS` syntax.  For instance, from the example before, I would call `conversation.getMemento( includes = [ "unreadMessages AS unread" ] )`  and the resulting memento would have an `unread` key instead of an `unreadMessages` key.

I'm open to alternatives as well, but I do this enough that I'd love a first party way of renaming keys easily.

**Comment by jclausen** [comment]
I'm not sure I see an issue with this, as a custom getter method ( e.g. `getUnread` ) would handle a difference in naming, just as easily.   For the workarounds that are already available, I'm not sure the juice is worth the squeeze on this one.   

If we did do some sort of re-aliasing in the memento, however, I think the colon designator ( which we use in ORM property lists ) would be less verbose and wouldn't have whitespace separation to deal with:  `conversation.getMemento( includes="createdTime,unreadMessages:unread,someOtherProperty" )`

**Comment by lmajano** [comment]
I agree with @jclausen that you can just as easily create a custom getter method as a workaround. However, I do quite like that in Hibernate it allows me to alias properties by using the `:` designator like @jclausen mentioned above. 

So if we do this, I would say that we should follow that designator: `unreadMessages:unread`.

**Comment by jclausen** [comment]
I think this one is closed now, right, since we added aliasing in v2.5.0?  https://github.com/coldbox-modules/mementifier/blob/development/changelog.md
