### ISSUE TITLE
Composite keys and no default includes

### ISSUE THREAD

**Issue by nockhigan** [coldbox-modules/mementifier#21]
Line 212 on interceptors/mementifier.cfc should be:

} else if ( entityMd.getIdentifierType().isComponentType() ) {

Otherwise this fails for entities with composite keys that do not have default includes defined for them.

**Comment by lmajano** [comment]
Thanks @nockhigan fixed now on `be` 
https://github.com/coldbox-modules/mementifier/commit/bc1ac837127f3440a257f4b147be18536975fe3e
