### ISSUE TITLE
DefaultIncludes = ["*"] getMemento returning unwanted ORM properties

### ISSUE THREAD

**Issue by nockhigan** [coldbox-modules/mementifier#22]
When setting defaultIncludes = ["*"] on a model a number of properties from the ORM object are being included which probably shouldn't be when calling the getMemento function on the object. ORM, ORMEventHandler, beanPopulator, logger, and a number of other properties are being returned by the getMemento function. When setting specific defaultIncludes or when not setting the defaultInclude value at all, these properties aren't being returned. So I would assume this isn't the intended behavior.

This looks like an issue with the filter of the $getDeepProperties array that happens on line 244 of the Mementifier.cfc interceptor. Adding a line to the return statement to check for !arguments.item.keyExists( "persistent" ) && fixes the issue.

**Comment by jclausen** [comment]
The `persistent` attribute check will probably not work because some devs will explicitly label them ( e.g. mapped superclasses ).  

You would probably want to do something like check the `getEntityMetadata().getPropertyNames()` array for persistent property keys, instead.

**Comment by nockhigan** [comment]
Yeah that's probably a better way of doing it.

Changing that return statement to:

!arguments.item.keyExists( "inject" ) &&
ArrayFindNoCase( getEntityMetadata( this ).getPropertyNames(), arguments.item.name ) &&
!thisMemento.defaultExcludes.findNoCase( arguments.item.name )

fixes things for me
