### ISSUE TITLE
ormAutoIncludes defaults to true which enables undocumented "referral" dependency on cborm

### ISSUE THREAD

**Issue by gpickin** [coldbox-modules/mementifier#29]
Right now, if you install mementifier, it has no dependencies... but out of the box, with no config, it defaulst `ormAutoIncludes` to `true`, which means it tries to use cborm to get the base orm service here

https://github.com/coldbox-modules/mementifier/blob/development/interceptors/Mementifier.cfc#L187 

I think we should not default this to `true`

**Comment by lmajano** [comment]
This is now addressed in 3.1.0.  It detected the `cborm` module. And if not installed, it disables the feature.
