### ISSUE TITLE
getMemento() converts string "YES" and "No" to boolean in JSON output

### ISSUE THREAD

**Issue by myleslee** [coldbox-modules/mementifier#35]
![Screenshot 2023-02-26 at 11 28 15](https://user-images.githubusercontent.com/108758/221390762-2916a5c4-32fd-47ca-81bc-514815cb0dfc.png)

It seems that `SerializeJSON()` works fine but `getMemento()` doesn't.

Reproduction code: 

```models\Employee.cfc
// models\Employee.cfc
component persistent="true" table="Employee" extends="cborm.models.ActiveEntity" {
  property property name="id" fieldtype="id" generator="native";
  property name="firstname";
  property name="lastname";
}
```

```handlers\main.cfc
// handlers\main.cfc
component extends="coldbox.system.EventHandler" {

	function index( event, rc, prc ) {
		rc.FirstName = "YES"
		rc.LastName  = "NO"

		dump(
			var=DeSerializeJSON(
				SerializeJSON(rc)
			),
			label="SerializeJSON"
		)

		prc.entity = getInstance("Employee").new(rc)
		prc.entity.save()
		dump(
			var=prc.entity.getMemento(),
			label="getMemento"
		)

		dump(
			QueryExecute("SELECT * FROM Employee WHERE ID = ?",[prc.entity.getID()])
		)

	}
}
```
System Info:
```
Lucee 5.3.10.97
coldbox-6.8.1+5-202208111517
cborm-4.3.2+75
mementifier-3.2.0+28
```
![Screenshot 2023-02-26 at 11 28 00](https://user-images.githubusercontent.com/108758/221390894-c5b61dd6-e78a-43dd-8f73-4d12fd42a81d.png)

**Comment by lmajano** [comment]
@bdw429s I can't remember the reason for this, can you remind me.

**Comment by jclausen** [comment]
That is code is still very much needed for Adobe.

**Comment by lmajano** [comment]
Well, I think we have to think about it, because if you are using a string called "yes". I think it's impossible to tell if it's a string or boolean since it can be both

**Comment by jclausen** [comment]
What is the use case for _not_ using those two strings, on their own, as non-booleans?  To me a mapper can handle the string conversion if needed, and the struct metadata can be put for that key to cast it as a string.

**Comment by bdw429s** [comment]
@jclausen Can you provide a simple repro case that shows where the code is needed for Adobe?  In my understanding, Adobe has had correct serialization of booleans since version 2018 so long as your original datatype was correct.  Please help me understand where it's still broken so we can be on the same page about it. 

This code sample returns the same result on Lucee 5, ACF 2021, and ACF 2018 on trycf
```
writedump( serializeJSON( [ 'yes' ] ) )
writedump( serializeJSON( [ 'true' ] ) )
writedump( serializeJSON( [ true ] ) )
```
which is 
```
["yes"]
["true"]
[true]
```
I have to go all the way back to ACF 2016 before its butchered.  So maybe we're talking about different things here.

**Comment by myleslee** [comment]
Is it possible to add a switch so one can decide if the Boolean-conversion feature is desired or not?

I'm not sure how to use MAPPER as a workaround. 

In my model, I tried 
```
this.memento = {
    defaultIncludes = [
      "SpareGroup"
    ],
    mappers = {
      "SpareGroup": function( item ){ systemOutput(['mapper.item', item]); return item },
    }
  }
```

And in the console, the output is 
<img width="240" alt="Screenshot 2023-03-17 at 11 19 33" src="https://user-images.githubusercontent.com/108758/225804244-d525139e-621f-4fed-b0b4-c81f1c530c49.png">

In my database, the `SpareGroup` column stores values of `Yes`,`No` and other values.

As you can see, I don't have a chance to get the original value in the Mapper.  

Even though the Mapper would work, I don't think it's feasible to apply to all my models because there are too many of them.
