### ISSUE TITLE
mementifier fails on ORM collection property

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/mementifier#4]
e.g. this one
`property name="accessorArray" fieldtype="collection" type="array" table="resourceAccessors" fkcolumn="Resource_fk" elementcolumn="AccessorId" elementType="string";`

I was expecting this would work because it is a simple array of string values. But I guess an array type brings you to $buildNestedMementoList which assumes a list of objects?

Of course this can be circumvented by overriding memento(), so it is not really important. I was just not expecting this to fail with a cryptic error message. It is failing on this part
```	// Array Collections
			if( isArray( thisValue ) ){
				// Map Items into result object
				result[ item ] = [];
				for( var thisIndex = 1; thisIndex <= arrayLen( thisValue ); thisIndex++ ){
					result[ item ][ thisIndex ] = thisValue[ thisIndex ].getMemento(
						includes 		= $buildNestedMementoList( includes, item ),
						excludes 		= $buildNestedMementoList( excludes, item ),
						mappers 		= mappers,
						defaults 		= defaults,
						ignoreDefaults 	= ignoreDefaults
					);
				}
			}
```

**Comment by MordantWastrel** [comment]
We ran into this as well. About to submit a PR to deal with it after talking with Luis
