### ISSUE TITLE
ACF11 Compat - Member Functions

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/mementifier#6]
.listLen and .listFirst and probably .listDeleteAt are unsupported in ACF11.

We can submit a PR to fix this later this week or if you want to accept or reject our existing PR first.

**Comment by MordantWastrel** [comment]
@lmajano In ACF11, this is broken again in 1.7 from the addition on the .len() member function.

**Comment by lmajano** [comment]
Argggg. I might have to deprecate cf11

**Comment by MordantWastrel** [comment]
Fine with me - we should be completely off of it within a month. Just maybe should be clearly marked and a 2.0?

**Comment by lmajano** [comment]
It's building now https://travis-ci.org/coldbox-modules/mementifier/builds/546946051
